// Unit tests for chart.c + collectors.c. No Gtk needed.
//   make test
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

#include "chart.h"
#include "collectors.h"
#include "strip.h"

static int dbl_eq(double a, double b) { return fabs(a - b) < 1e-9; }

// Mirrors chart.py push() accumulation for the same input.
static void test_chart_accumulation(void) {
  SmChart c;
  const char *colors[] = {"#0072b3", "#0092e6"};
  assert(sm_chart_init(&c, 10, 10, colors, 2, 100.0) == 0);
  double v1[] = {10.0, 5.0};
  double v2[] = {20.0, 0.0};
  sm_chart_push(&c, v1);
  sm_chart_push(&c, v2);
  // layer0: raw values; layer1: stacked, non-positive ignored.
  assert(dbl_eq(c.data[0 * 10 + 0], 10.0));
  assert(dbl_eq(c.data[0 * 10 + 1], 20.0));
  assert(dbl_eq(c.data[1 * 10 + 0], 15.0));
  assert(dbl_eq(c.data[1 * 10 + 1], 20.0));
  assert(c.count == 2);
  sm_chart_free(&c);
}

static void test_chart_ymax(void) {
  SmChart c;
  const char *colors[] = {"#ff0000"};
  // fixed max wins
  assert(sm_chart_init(&c, 10, 10, colors, 1, 42.0) == 0);
  assert(dbl_eq(sm_chart_ymax(&c), 42.0));
  sm_chart_free(&c);
  // auto: next power of two, min 1.0
  assert(sm_chart_init(&c, 10, 10, colors, 1, -1.0) == 0);
  assert(dbl_eq(sm_chart_ymax(&c), 1.0));  // empty
  double v[] = {50.0};
  sm_chart_push(&c, v);
  assert(dbl_eq(sm_chart_ymax(&c), 64.0));
  sm_chart_free(&c);
}

static void test_chart_overflow(void) {
  SmChart c;
  const char *colors[] = {"#ff0000"};
  assert(sm_chart_init(&c, 4, 10, colors, 1, -1.0) == 0);
  for (int i = 1; i <= 6; i++) {
    double v[] = {(double)i * 10.0};
    sm_chart_push(&c, v);
  }
  assert(c.count == 4);
  assert(dbl_eq(c.data[0], 30.0));
  assert(dbl_eq(c.data[3], 60.0));
  sm_chart_free(&c);
}

static void test_parse_color(void) {
  SmColor col;
  assert(sm_parse_color("#ffffff16", &col) == 0);
  assert(dbl_eq(col.r, 1.0) && col.a < 0.2);
  assert(sm_parse_color("#0072b3", &col) == 0);
  assert(dbl_eq(col.r, 0x00 / 255.0) && dbl_eq(col.g, 0x72 / 255.0));
  assert(sm_parse_color("nope", &col) != 0);
  assert(sm_parse_color(NULL, &col) != 0);
}

// Cross-check against chart.py with a shared deterministic sequence.
static void test_against_python_reference(void) {
  // Generated by: python3 -c "
  // from chart import StackedChart
  // c = StackedChart(100, 22, ['#0072b3','#0092e6','#00a3ff','#002f3d','#001d26'])
  // import math
  // seq = [[20+30*math.sin(t/99*2*math.pi), 8+5*math.cos(t/99*math.pi),
  //         max(0,5-t%7), 3 if t%11==0 else 1, 0] for t in range(100)]
  // [c.push(v) for v in seq]
  // print(repr([round(x,9) for x in c._data[0][-3:]]))
  // print(repr([round(x,9) for x in c._data[4][-3:]]))"
  SmChart c;
  const char *colors[] = {"#0072b3", "#0092e6", "#00a3ff", "#002f3d", "#001d26"};
  assert(sm_chart_init(&c, 100, 22, colors, 5, -1.0) == 0);
  for (int t = 0; t < 100; t++) {
    double phase = (double)t / 99.0;
    double vals[5] = {
        20 + 30 * sin(phase * 2 * M_PI),
        8 + 5 * cos(phase * M_PI),
        (double)(5 - t % 7 > 0 ? 5 - t % 7 : 0),
        (t % 11 == 0) ? 3.0 : 1.0,
        0.0,
    };
    sm_chart_push(&c, vals);
  }
  char exp0[256], exp4[256];
  snprintf(exp0, sizeof(exp0), "%.6f %.6f %.6f", c.data[0 * 100 + 97],
           c.data[0 * 100 + 98], c.data[0 * 100 + 99]);
  snprintf(exp4, sizeof(exp4), "%.6f %.6f %.6f", c.data[4 * 100 + 97],
           c.data[4 * 100 + 98], c.data[4 * 100 + 99]);
  // Values below were produced by chart.py for the identical sequence.
  double l0[3], l4[3];
  sscanf(exp0, "%lf %lf %lf", &l0[0], &l0[1], &l0[2]);
  sscanf(exp4, "%lf %lf %lf", &l4[0], &l4[1], &l4[2]);
  assert(fabs(l0[0] - 16.202226393) < 1e-6);
  assert(fabs(l0[1] - 18.097282410) < 1e-6);
  assert(fabs(l0[2] - 20.0) < 1e-6);
  assert(fabs(l4[0] - 20.212293010) < 1e-6);
  assert(fabs(l4[1] - 27.099799698) < 1e-6);
  assert(fabs(l4[2] - 30.0) < 1e-6);
  sm_chart_free(&c);
}

static void test_label_draws_ink(void) {
  cairo_surface_t *s = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, 64, 30);
  cairo_t *cr = cairo_create(s);
  cairo_set_source_rgba(cr, 0, 0, 0, 0);
  cairo_set_operator(cr, CAIRO_OPERATOR_SOURCE);
  cairo_paint(cr);
  cairo_set_operator(cr, CAIRO_OPERATOR_OVER);
  sm_draw_label(cr, "cpu", 30, SM_LABEL_RGBA, SM_LABEL_FONT_SIZE);
  // Overlong text is truncated to the strip height, staying in-slot.
  sm_draw_label(cr, "averylonglabelname", 30, SM_LABEL_RGBA, SM_LABEL_FONT_SIZE);
  // Degenerate inputs must neither crash nor paint.
  sm_draw_label(cr, "", 30, SM_LABEL_RGBA, SM_LABEL_FONT_SIZE);
  sm_draw_label(cr, NULL, 30, SM_LABEL_RGBA, SM_LABEL_FONT_SIZE);
  sm_draw_label(NULL, "cpu", 30, SM_LABEL_RGBA, SM_LABEL_FONT_SIZE);
  cairo_surface_flush(s);
  unsigned char *d = cairo_image_surface_get_data(s);
  int stride = cairo_image_surface_get_stride(s);
  int ink = 0, outside = 0;
  for (int y = 0; y < 30; y++) {
    for (int x = 0; x < 64; x++) {
      // ARGB32 on little-endian stores bytes as B,G,R,A.
      if (d[y * stride + x * 4 + 3] > 0) {
        ink++;
        if (x >= SM_LABEL_PX) outside++;
      }
    }
  }
  assert(ink > 20);     // real glyph pixels landed
  assert(outside == 0);  // ... and stayed inside the label slot
  cairo_destroy(cr);
  cairo_surface_destroy(s);
  assert(sm_element_width(1, 100) == SM_LABEL_PX + 100);
  assert(sm_element_width(0, 100) == 100);
}

static void test_collectors_live(void) {
  CpuState cpu;
  memset(&cpu, 0, sizeof(cpu));
  double out5[5];
  assert(cpu_sample(&cpu, out5) == 0);  // primes
  struct timespec req = {0, 200 * 1000 * 1000};
  nanosleep(&req, NULL);
  assert(cpu_sample(&cpu, out5) == 1);
  // Stack layout mirrors collectors.py: [user, system, nice, iowait, other]
  // where other = 100 - (all incl. idle), so the layers sum to <= 100.
  double total = out5[0] + out5[1] + out5[2] + out5[3] + out5[4];
  assert(total >= 0.0 && total <= 100.0 + 1e-6);
  for (int i = 0; i < 5; i++) assert(out5[i] >= 0.0 && out5[i] <= 100.0);

  double out3[3];
  assert(mem_sample(out3) == 1);
  assert(out3[0] >= 0 && out3[0] <= 1 && out3[1] >= 0 && out3[2] >= 0);
  assert(out3[0] + out3[1] + out3[2] <= 1.0 + 1e-9);

  NetState net;
  memset(&net, 0, sizeof(net));
  assert(net_sample(&net, out5) == 0);  // primes
  nanosleep(&req, NULL);
  assert(net_sample(&net, out5) == 1);
  for (int i = 0; i < 5; i++) assert(out5[i] >= 0.0);

  // NULL guards never crash.
  assert(cpu_sample(NULL, out5) == 0);
  assert(mem_sample(NULL) == 0);
  assert(net_sample(NULL, out5) == 0);
}

int main(void) {
  test_chart_accumulation();
  test_chart_ymax();
  test_chart_overflow();
  test_parse_color();
  test_against_python_reference();
  test_label_draws_ink();
  test_collectors_live();
  printf("cffi logic tests: OK\n");
  return 0;
}
